# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'scopy.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1149, 776)
        MainWindow.setStyleSheet("\n"
"      /*\n"
"      Ubuntu Style Sheet for QT Applications\n"
"Author: Jaime A. Quiroga P.\n"
"Company: GTRONICK\n"
"Last updated: 01/10/2021 (dd/mm/yyyy), 15:18.\n"
"Available at: https://github.com/GTRONICK/QSS/blob/master/Ubuntu.qss\n"
"*/\n"
"QMainWindow {\n"
"    background-color:#f0f0f0;\n"
"}\n"
"QCheckBox {\n"
"    padding:2px;\n"
"}\n"
"QCheckBox:hover {\n"
"    border:1px solid rgb(255,150,60);\n"
"    border-radius:4px;\n"
"    padding: 1px;\n"
"    background-color:qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(190, 90, 50, 50), stop:1 rgba(250, 130, 40, 50));\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    border:1px solid rgb(246, 134, 86);\n"
"    border-radius:4px;\n"
"      background-color:rgb(246, 134, 86)\n"
"}\n"
"QCheckBox::indicator:unchecked {\n"
"    border-width:1px solid rgb(246, 134, 86);\n"
"    border-radius:4px;\n"
"      background-color:rgb(255,255,255);\n"
"}\n"
"QColorDialog {\n"
"    background-color:#f0f0f0;\n"
"}\n"
"QComboBox {\n"
"    color:rgb(81,72,65);\n"
"    background: #ffffff;\n"
"}\n"
"QComboBox:editable {\n"
"    selection-color:rgb(81,72,65);\n"
"    selection-background-color: #ffffff;\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    selection-color: #ffffff;\n"
"    selection-background-color: rgb(246, 134, 86);\n"
"}\n"
"QComboBox:!editable:on, QComboBox::drop-down:editable:on {\n"
"    color:  #1e1d23;    \n"
"}\n"
"QDateTimeEdit, QDateEdit, QDoubleSpinBox, QFontComboBox {\n"
"    color:rgb(81,72,65);\n"
"    background-color: #ffffff;\n"
"}\n"
"\n"
"QDialog {\n"
"    background-color:#f0f0f0;\n"
"}\n"
"\n"
"QLabel,QLineEdit {\n"
"    color:rgb(17,17,17);\n"
"}\n"
"QLineEdit {\n"
"    background-color:rgb(255,255,255);\n"
"    selection-background-color:rgb(236,116,64);\n"
"}\n"
"QMenuBar {\n"
"    color:rgb(223,219,210);\n"
"    background-color:rgb(65,64,59);\n"
"}\n"
"QMenuBar::item {\n"
"    padding-top:4px;\n"
"    padding-left:4px;\n"
"    padding-right:4px;\n"
"    color:rgb(223,219,210);\n"
"    background-color:rgb(65,64,59);\n"
"}\n"
"QMenuBar::item:selected {\n"
"    color:rgb(255,255,255);\n"
"    padding-top:2px;\n"
"    padding-left:2px;\n"
"    padding-right:2px;\n"
"    border-top-width:2px;\n"
"    border-left-width:2px;\n"
"    border-right-width:2px;\n"
"    border-top-right-radius:4px;\n"
"    border-top-left-radius:4px;\n"
"    border-style:solid;\n"
"    background-color:rgb(65,64,59);\n"
"    border-top-color: rgb(47,47,44);\n"
"    border-right-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(90, 87, 78, 255), stop:1 rgba(47,47,44, 255));\n"
"    border-left-color:  qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0 rgba(90, 87, 78, 255), stop:1 rgba(47,47,44, 255));\n"
"}\n"
"QMenu {\n"
"    color:rgb(223,219,210);\n"
"    background-color:rgb(65,64,59);\n"
"}\n"
"QMenu::item {\n"
"    color:rgb(223,219,210);\n"
"    padding:4px 10px 4px 20px;\n"
"}\n"
"QMenu::item:selected {\n"
"    color:rgb(255,255,255);\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(225, 108, 54, 255), stop:1 rgba(246, 134, 86, 255));\n"
"    border-style:solid;\n"
"    border-width:3px;\n"
"    padding:4px 7px 4px 17px;\n"
"    border-bottom-color:qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(175,85,48,255), stop:1 rgba(236,114,67, 255));\n"
"    border-top-color:qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(253,156,113,255), stop:1 rgba(205,90,46, 255));\n"
"    border-right-color:qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgba(253,156,113,255), stop:1 rgba(205,90,46, 255));\n"
"    border-left-color:qlineargradient(spread:pad, x1:1, y1:0.5, x2:0, y2:0.5, stop:0 rgba(253,156,113,255), stop:1 rgba(205,90,46, 255));\n"
"}\n"
"QPlainTextEdit {\n"
"    border: 1px solid transparent;\n"
"    color:rgb(17,17,17);\n"
"    selection-background-color:rgb(236,116,64);\n"
"    background-color: #FFFFFF;\n"
"}\n"
"QProgressBar {\n"
"    text-align: center;\n"
"    color: rgb(0, 0, 0);\n"
"    border: 1px inset rgb(150,150,150); \n"
"    border-radius: 10px;\n"
"    background-color:rgb(221,221,219);\n"
"}\n"
"QProgressBar::chunk:horizontal {\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(225, 108, 54, 255), stop:1 rgba(246, 134, 86, 255));\n"
"    border:1px solid;\n"
"    border-radius:8px;\n"
"    border-bottom-color:qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(175,85,48,255), stop:1 rgba(236,114,67, 255));\n"
"    border-top-color:qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(253,156,113,255), stop:1 rgba(205,90,46, 255));\n"
"    border-right-color:qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgba(253,156,113,255), stop:1 rgba(205,90,46, 255));\n"
"    border-left-color:qlineargradient(spread:pad, x1:1, y1:0.5, x2:0, y2:0.5, stop:0 rgba(253,156,113,255), stop:1 rgba(205,90,46, 255));\n"
"}\n"
"QPushButton{\n"
"    color:rgb(17,17,17);\n"
"    border-width: 1px;\n"
"    border-radius: 6px;\n"
"    border-bottom-color: rgb(150,150,150);\n"
"    border-right-color: rgb(165,165,165);\n"
"    border-left-color: rgb(165,165,165);\n"
"    border-top-color: rgb(180,180,180);\n"
"    border-style: solid;\n"
"    padding: 4px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(220, 220, 220, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}\n"
"QPushButton:hover{\n"
"    color:rgb(17,17,17);\n"
"    border-width: 1px;\n"
"    border-radius:6px;\n"
"    border-top-color: rgb(255,150,60);\n"
"    border-right-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(200, 70, 20, 255), stop:1 rgba(255,150,60, 255));\n"
"    border-left-color:  qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0 rgba(200, 70, 20, 255), stop:1 rgba(255,150,60, 255));\n"
"    border-bottom-color: rgb(200,70,20);\n"
"    border-style: solid;\n"
"    padding: 2px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(220, 220, 220, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}\n"
"QPushButton:default{\n"
"    color:rgb(17,17,17);\n"
"    border-width: 1px;\n"
"    border-radius:6px;\n"
"    border-top-color: rgb(255,150,60);\n"
"    border-right-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(200, 70, 20, 255), stop:1 rgba(255,150,60, 255));\n"
"    border-left-color:  qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0 rgba(200, 70, 20, 255), stop:1 rgba(255,150,60, 255));\n"
"    border-bottom-color: rgb(200,70,20);\n"
"    border-style: solid;\n"
"    padding: 2px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(220, 220, 220, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}\n"
"QPushButton:pressed{\n"
"    color:rgb(17,17,17);\n"
"    border-width: 1px;\n"
"    border-radius: 6px;\n"
"    border-width: 1px;\n"
"    border-top-color: rgba(255,150,60,200);\n"
"    border-right-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(200, 70, 20, 255), stop:1 rgba(255,150,60, 200));\n"
"    border-left-color:  qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0 rgba(200, 70, 20, 255), stop:1 rgba(255,150,60, 200));\n"
"    border-bottom-color: rgba(200,70,20,200);\n"
"    border-style: solid;\n"
"    padding: 2px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 rgba(220, 220, 220, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}\n"
"QPushButton:disabled{\n"
"    color:rgb(174,167,159);\n"
"    border-width: 1px;\n"
"    border-radius: 6px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(200, 200, 200, 255), stop:1 rgba(230, 230, 230, 255));\n"
"}\n"
"QRadioButton {\n"
"    padding: 1px;\n"
"}\n"
"QRadioButton::indicator:checked {\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    border-style:solid;\n"
"    border-radius:5px;\n"
"    border-width: 1px;\n"
"    border-color: rgba(246, 134, 86, 255);\n"
"    color: #a9b7c6;\n"
"    background-color:rgba(246, 134, 86, 255);\n"
"}\n"
"QRadioButton::indicator:!checked {\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    border-style:solid;\n"
"    border-radius:5px;\n"
"    border-width: 1px;\n"
"    border-color: rgb(246, 134, 86);\n"
"    color: #a9b7c6;\n"
"    background-color: transparent;\n"
"}\n"
"QScrollArea {\n"
"    color: white;\n"
"    background-color:#f0f0f0;\n"
"}\n"
"QSlider::groove {\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: rgb(207,207,207);\n"
"}\n"
"QSlider::groove:horizontal {\n"
"    height: 5px;\n"
"    background: rgb(246, 134, 86);\n"
"}\n"
"QSlider::groove:vertical {\n"
"    width: 5px;\n"
"    background: rgb(246, 134, 86);\n"
"}\n"
"QSlider::handle:horizontal {\n"
"    background: rgb(253,253,253);\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: rgb(207,207,207);\n"
"    width: 12px;\n"
"    margin: -5px 0;\n"
"    border-radius: 7px;\n"
"}\n"
"QSlider::handle:vertical {\n"
"    background: rgb(253,253,253);\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: rgb(207,207,207);\n"
"    height: 12px;\n"
"    margin: 0 -5px;\n"
"    border-radius: 7px;\n"
"}\n"
"QSlider::add-page:horizontal, QSlider::add-page:vertical {\n"
"     background: white;\n"
"}\n"
"QSlider::sub-page:horizontal, QSlider::sub-page:vertical {\n"
"    background: rgb(246, 134, 86);\n"
"}\n"
"QStatusBar, QSpinBox {\n"
"    color:rgb(81,72,65);\n"
"}\n"
"QSpinBox {\n"
"    background-color: #ffffff;\n"
"}\n"
"QScrollBar:horizontal {\n"
"    max-height: 20px;\n"
"    border: 1px transparent;\n"
"    margin: 0px 20px 0px 20px;\n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"    background: rgb(253,253,253);\n"
"    border: 1px solid rgb(207,207,207);\n"
"    border-radius: 7px;\n"
"    min-width: 25px;\n"
"}\n"
"QScrollBar::handle:horizontal:hover {\n"
"    background: rgb(253,253,253);\n"
"    border: 1px solid rgb(255,150,60);\n"
"    border-radius: 7px;\n"
"    min-width: 25px;\n"
"}\n"
"QScrollBar::add-line:horizontal {\n"
"      border: 1px solid rgb(207,207,207);\n"
"      border-top-right-radius: 7px;\n"
"      border-top-left-radius: 7px;\n"
"      border-bottom-right-radius: 7px;\n"
"      background: rgb(255, 255, 255);\n"
"      width: 20px;\n"
"      subcontrol-position: right;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:horizontal:hover {\n"
"      border: 1px solid rgb(255,150,60);\n"
"      border-top-right-radius: 7px;\n"
"      border-top-left-radius: 7px;\n"
"      border-bottom-right-radius: 7px;\n"
"      background: rgb(255, 255, 255);\n"
"      width: 20px;\n"
"      subcontrol-position: right;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:horizontal:pressed {\n"
"      border: 1px solid grey;\n"
"      border-top-left-radius: 7px;\n"
"      border-top-right-radius: 7px;\n"
"      border-bottom-right-radius: 7px;\n"
"      background: rgb(231,231,231);\n"
"      width: 20px;\n"
"      subcontrol-position: right;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal {\n"
"      border: 1px solid rgb(207,207,207);\n"
"      border-top-right-radius: 7px;\n"
"      border-top-left-radius: 7px;\n"
"      border-bottom-left-radius: 7px;\n"
"      background: rgb(255, 255, 255);\n"
"      width: 20px;\n"
"      subcontrol-position: left;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal:hover {\n"
"      border: 1px solid rgb(255,150,60);\n"
"      border-top-right-radius: 7px;\n"
"      border-top-left-radius: 7px;\n"
"      border-bottom-left-radius: 7px;\n"
"      background: rgb(255, 255, 255);\n"
"      width: 20px;\n"
"      subcontrol-position: left;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal:pressed {\n"
"      border: 1px solid grey;\n"
"      border-top-right-radius: 7px;\n"
"      border-top-left-radius: 7px;\n"
"      border-bottom-left-radius: 7px;\n"
"      background: rgb(231,231,231);\n"
"      width: 20px;\n"
"      subcontrol-position: left;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::left-arrow:horizontal {\n"
"      border: 1px transparent grey;\n"
"      border-top-left-radius: 3px;\n"
"      border-bottom-left-radius: 3px;\n"
"      width: 6px;\n"
"      height: 6px;\n"
"      background: rgb(230,230,230);\n"
"}\n"
"QScrollBar::right-arrow:horizontal {\n"
"    border: 1px transparent grey;\n"
"    border-top-right-radius: 3px;\n"
"    border-bottom-right-radius: 3px;\n"
"      width: 6px;\n"
"      height: 6px;\n"
"     background: rgb(230,230,230);\n"
"}\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"     background: none;\n"
"} \n"
"QScrollBar:vertical {\n"
"    max-width: 20px;\n"
"    border: 1px transparent grey;\n"
"    margin: 20px 0px 20px 0px;\n"
"}\n"
"QScrollBar::add-line:vertical {\n"
"    border: 1px solid;\n"
"    border-color: rgb(207,207,207);\n"
"    border-bottom-right-radius: 7px;\n"
"    border-bottom-left-radius: 7px;\n"
"    border-top-left-radius: 7px;\n"
"    background: rgb(255, 255, 255);\n"
"      height: 20px;\n"
"      subcontrol-position: bottom;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {\n"
"      border: 1px solid;\n"
"      border-color: rgb(255,150,60);\n"
"      border-bottom-right-radius: 7px;\n"
"      border-bottom-left-radius: 7px;\n"
"      border-top-left-radius: 7px;\n"
"      background: rgb(255, 255, 255);\n"
"      height: 20px;\n"
"      subcontrol-position: bottom;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {\n"
"      border: 1px solid grey;\n"
"      border-bottom-left-radius: 7px;\n"
"      border-bottom-right-radius: 7px;\n"
"      border-top-left-radius: 7px;\n"
"      background: rgb(231,231,231);\n"
"      height: 20px;\n"
"      subcontrol-position: bottom;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical {\n"
"      border: 1px solid rgb(207,207,207);\n"
"      border-top-right-radius: 7px;\n"
"      border-top-left-radius: 7px;\n"
"      border-bottom-left-radius: 7px;\n"
"      background: rgb(255, 255, 255);\n"
"      height: 20px;\n"
"      subcontrol-position: top;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {\n"
"      border: 1px solid rgb(255,150,60);\n"
"      border-top-right-radius: 7px;\n"
"      border-top-left-radius: 7px;\n"
"      border-bottom-left-radius: 7px;\n"
"    background: rgb(255, 255, 255);\n"
"      height: 20px;\n"
"      subcontrol-position: top;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {\n"
"      border: 1px solid grey;\n"
"      border-top-left-radius: 7px;\n"
"      border-top-right-radius: 7px;\n"
"      background: rgb(231,231,231);\n"
"     height: 20px;\n"
"      subcontrol-position: top;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"    background: rgb(253,253,253);\n"
"    border: 1px solid rgb(207,207,207);\n"
"    border-radius: 7px;\n"
"    min-height: 25px;\n"
"}\n"
"QScrollBar::handle:vertical:hover {\n"
"    background: rgb(253,253,253);\n"
"    border: 1px solid rgb(255,150,60);\n"
"    border-radius: 7px;\n"
"    min-height: 25px;\n"
"}\n"
"QScrollBar::up-arrow:vertical {\n"
"    border: 1px transparent grey;\n"
"      border-top-left-radius: 3px;\n"
"    border-top-right-radius: 3px;\n"
"      width: 6px;\n"
"      height: 6px;\n"
"      background: rgb(230,230,230);\n"
"}\n"
"QScrollBar::down-arrow:vertical {\n"
"      border: 1px transparent grey;\n"
"      border-bottom-left-radius: 3px;\n"
"      border-bottom-right-radius: 3px;\n"
"      width: 6px;\n"
"      height: 6px;\n"
"      background: rgb(230,230,230);\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"      background: none;\n"
"}\n"
"QTabWidget {\n"
"    color:rgb(0,0,0);\n"
"    background-color:rgb(247,246,246);\n"
"}\n"
"QTabWidget::pane {\n"
"    border-color: rgb(180,180,180);\n"
"    background-color:rgb(247,246,246);\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"      border-radius: 6px;\n"
"}\n"
"QTabBar::tab {\n"
"    padding-left:4px;\n"
"    padding-right:4px;\n"
"    padding-bottom:2px;\n"
"    padding-top:2px;\n"
"    color:rgb(81,72,65);\n"
"      background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(221,218,217,255), stop:1 rgba(240,239,238,255));\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"      border-top-right-radius:4px;\n"
"    border-top-left-radius:4px;\n"
"    border-top-color: rgb(180,180,180);\n"
"    border-left-color: rgb(180,180,180);\n"
"    border-right-color: rgb(180,180,180);\n"
"    border-bottom-color: transparent;\n"
"}\n"
"QTabBar::tab:selected, QTabBar::tab:last:selected, QTabBar::tab:hover {\n"
"      background-color:rgb(247,246,246);\n"
"      margin-left: 0px;\n"
"      margin-right: 1px;\n"
"}\n"
"QTabBar::tab:!selected {\n"
"    margin-top: 1px;\n"
"    margin-right: 1px;\n"
"}\n"
"QTextEdit {\n"
"    border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color:transparent;\n"
"    color:rgb(17,17,17);\n"
"    selection-background-color:rgb(236,116,64);\n"
"}\n"
"QTimeEdit, QToolBox, QToolBox::tab, QToolBox::tab:selected {\n"
"    color:rgb(81,72,65);\n"
"    background-color: #ffffff;\n"
"}\n"
"    ")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_viewer = QtWidgets.QWidget()
        self.tab_viewer.setObjectName("tab_viewer")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_viewer)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_SNR = QtWidgets.QHBoxLayout()
        self.horizontalLayout_SNR.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_SNR.setObjectName("horizontalLayout_SNR")
        self.lbl_snr_level = QtWidgets.QLabel(self.tab_viewer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_snr_level.sizePolicy().hasHeightForWidth())
        self.lbl_snr_level.setSizePolicy(sizePolicy)
        self.lbl_snr_level.setMinimumSize(QtCore.QSize(200, 0))
        self.lbl_snr_level.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        self.lbl_snr_level.setFont(font)
        self.lbl_snr_level.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbl_snr_level.setObjectName("lbl_snr_level")
        self.horizontalLayout_SNR.addWidget(self.lbl_snr_level)
        self.dial_SNR = QtWidgets.QDial(self.tab_viewer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dial_SNR.sizePolicy().hasHeightForWidth())
        self.dial_SNR.setSizePolicy(sizePolicy)
        self.dial_SNR.setMaximumSize(QtCore.QSize(200, 16777215))
        self.dial_SNR.setMinimum(1)
        self.dial_SNR.setMaximum(30)
        self.dial_SNR.setInvertedAppearance(False)
        self.dial_SNR.setNotchesVisible(True)
        self.dial_SNR.setObjectName("dial_SNR")
        self.horizontalLayout_SNR.addWidget(self.dial_SNR)
        self.gridLayout.addLayout(self.horizontalLayout_SNR, 1, 0, 1, 1)
        self.verticalLayout_sampling_freq = QtWidgets.QVBoxLayout()
        self.verticalLayout_sampling_freq.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_sampling_freq.setObjectName("verticalLayout_sampling_freq")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_sampling_freq.addItem(spacerItem)
        self.btn_open_signal = QtWidgets.QPushButton(self.tab_viewer)
        self.btn_open_signal.setObjectName("btn_open_signal")
        self.verticalLayout_sampling_freq.addWidget(self.btn_open_signal)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_sampling_freq.addItem(spacerItem1)
        self.line_2 = QtWidgets.QFrame(self.tab_viewer)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_sampling_freq.addWidget(self.line_2)
        self.label_original_frequency = QtWidgets.QLabel(self.tab_viewer)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        self.label_original_frequency.setFont(font)
        self.label_original_frequency.setObjectName("label_original_frequency")
        self.verticalLayout_sampling_freq.addWidget(self.label_original_frequency)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_sampling_freq.addItem(spacerItem2)
        self.label_sampling_frequency = QtWidgets.QLabel(self.tab_viewer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_sampling_frequency.sizePolicy().hasHeightForWidth())
        self.label_sampling_frequency.setSizePolicy(sizePolicy)
        self.label_sampling_frequency.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        self.label_sampling_frequency.setFont(font)
        self.label_sampling_frequency.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_sampling_frequency.setObjectName("label_sampling_frequency")
        self.verticalLayout_sampling_freq.addWidget(self.label_sampling_frequency)
        self.horizontalSlider_sample_freq = QtWidgets.QSlider(self.tab_viewer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalSlider_sample_freq.sizePolicy().hasHeightForWidth())
        self.horizontalSlider_sample_freq.setSizePolicy(sizePolicy)
        self.horizontalSlider_sample_freq.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_sample_freq.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.horizontalSlider_sample_freq.setTickInterval(5)
        self.horizontalSlider_sample_freq.setObjectName("horizontalSlider_sample_freq")
        self.verticalLayout_sampling_freq.addWidget(self.horizontalSlider_sample_freq)
        self.gridLayout.addLayout(self.verticalLayout_sampling_freq, 0, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 2, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 2, 1)
        self.line = QtWidgets.QFrame(self.tab_viewer)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 0, 1, 2, 2)
        self.splitter_2 = QtWidgets.QSplitter(self.tab_viewer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter_2.sizePolicy().hasHeightForWidth())
        self.splitter_2.setSizePolicy(sizePolicy)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.layoutWidget = QtWidgets.QWidget(self.splitter_2)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_main_signal = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.label_main_signal.setFont(font)
        self.label_main_signal.setIndent(5)
        self.label_main_signal.setObjectName("label_main_signal")
        self.verticalLayout_3.addWidget(self.label_main_signal)
        self.plot_widget_main_signal = PlotWidget(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plot_widget_main_signal.sizePolicy().hasHeightForWidth())
        self.plot_widget_main_signal.setSizePolicy(sizePolicy)
        self.plot_widget_main_signal.setMinimumSize(QtCore.QSize(500, 180))
        self.plot_widget_main_signal.setObjectName("plot_widget_main_signal")
        self.verticalLayout_3.addWidget(self.plot_widget_main_signal)
        self.layoutWidget1 = QtWidgets.QWidget(self.splitter_2)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_constructed_signal = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.label_constructed_signal.setFont(font)
        self.label_constructed_signal.setIndent(5)
        self.label_constructed_signal.setObjectName("label_constructed_signal")
        self.verticalLayout_4.addWidget(self.label_constructed_signal)
        self.plot_widget_restored_signal = PlotWidget(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plot_widget_restored_signal.sizePolicy().hasHeightForWidth())
        self.plot_widget_restored_signal.setSizePolicy(sizePolicy)
        self.plot_widget_restored_signal.setMinimumSize(QtCore.QSize(500, 180))
        self.plot_widget_restored_signal.setObjectName("plot_widget_restored_signal")
        self.verticalLayout_4.addWidget(self.plot_widget_restored_signal)
        self.layoutWidget2 = QtWidgets.QWidget(self.splitter_2)
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_const_err = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.label_const_err.setFont(font)
        self.label_const_err.setIndent(5)
        self.label_const_err.setObjectName("label_const_err")
        self.verticalLayout_5.addWidget(self.label_const_err)
        self.plot_widget_difference = PlotWidget(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plot_widget_difference.sizePolicy().hasHeightForWidth())
        self.plot_widget_difference.setSizePolicy(sizePolicy)
        self.plot_widget_difference.setMinimumSize(QtCore.QSize(500, 180))
        self.plot_widget_difference.setObjectName("plot_widget_difference")
        self.verticalLayout_5.addWidget(self.plot_widget_difference)
        self.gridLayout_2.addWidget(self.splitter_2, 0, 3, 1, 1)
        self.tabWidget.addTab(self.tab_viewer, "")
        self.tab_composer = QtWidgets.QWidget()
        self.tab_composer.setObjectName("tab_composer")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_composer)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.widget_plots = QtWidgets.QWidget(self.tab_composer)
        self.widget_plots.setObjectName("widget_plots")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget_plots)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.widget_plots)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(300, 30))
        self.label.setIndent(5)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.plot_widget_component = PlotWidget(self.widget_plots)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plot_widget_component.sizePolicy().hasHeightForWidth())
        self.plot_widget_component.setSizePolicy(sizePolicy)
        self.plot_widget_component.setMinimumSize(QtCore.QSize(0, 50))
        self.plot_widget_component.setBaseSize(QtCore.QSize(0, 200))
        self.plot_widget_component.setObjectName("plot_widget_component")
        self.verticalLayout.addWidget(self.plot_widget_component)
        self.verticalLayout_6.addLayout(self.verticalLayout)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.widget_plots)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMaximumSize(QtCore.QSize(300, 30))
        self.label_2.setIndent(5)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.plot_widget_composed = PlotWidget(self.widget_plots)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plot_widget_composed.sizePolicy().hasHeightForWidth())
        self.plot_widget_composed.setSizePolicy(sizePolicy)
        self.plot_widget_composed.setMinimumSize(QtCore.QSize(0, 50))
        self.plot_widget_composed.setBaseSize(QtCore.QSize(0, 200))
        self.plot_widget_composed.setObjectName("plot_widget_composed")
        self.verticalLayout_2.addWidget(self.plot_widget_composed)
        self.gridLayout_7.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.btn_compose = QtWidgets.QPushButton(self.widget_plots)
        self.btn_compose.setMinimumSize(QtCore.QSize(200, 0))
        self.btn_compose.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btn_compose.setObjectName("btn_compose")
        self.gridLayout_7.addWidget(self.btn_compose, 1, 0, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_7)
        self.gridLayout_3.addWidget(self.widget_plots, 0, 0, 1, 1)
        self.widget_comps = QtWidgets.QWidget(self.tab_composer)
        self.widget_comps.setMaximumSize(QtCore.QSize(400, 16777215))
        self.widget_comps.setObjectName("widget_comps")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.widget_comps)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.gridLayout_settings = QtWidgets.QGridLayout()
        self.gridLayout_settings.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.gridLayout_settings.setObjectName("gridLayout_settings")
        self.btn_remove_component = QtWidgets.QPushButton(self.widget_comps)
        self.btn_remove_component.setObjectName("btn_remove_component")
        self.gridLayout_settings.addWidget(self.btn_remove_component, 4, 1, 1, 1)
        self.label_comp_stats = QtWidgets.QLabel(self.widget_comps)
        self.label_comp_stats.setObjectName("label_comp_stats")
        self.gridLayout_settings.addWidget(self.label_comp_stats, 2, 0, 1, 1)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_phase_2 = QtWidgets.QLabel(self.widget_comps)
        self.label_phase_2.setObjectName("label_phase_2")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_phase_2)
        self.field_name = QtWidgets.QLineEdit(self.widget_comps)
        self.field_name.setMaximumSize(QtCore.QSize(150, 16777215))
        self.field_name.setObjectName("field_name")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.field_name)
        self.label_amp = QtWidgets.QLabel(self.widget_comps)
        self.label_amp.setObjectName("label_amp")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_amp)
        self.field_amplitude = QtWidgets.QLineEdit(self.widget_comps)
        self.field_amplitude.setMaximumSize(QtCore.QSize(150, 16777215))
        self.field_amplitude.setObjectName("field_amplitude")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.field_amplitude)
        self.label_freq = QtWidgets.QLabel(self.widget_comps)
        self.label_freq.setObjectName("label_freq")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_freq)
        self.field_frequency = QtWidgets.QLineEdit(self.widget_comps)
        self.field_frequency.setMaximumSize(QtCore.QSize(150, 16777215))
        self.field_frequency.setObjectName("field_frequency")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.field_frequency)
        self.label_phase = QtWidgets.QLabel(self.widget_comps)
        self.label_phase.setObjectName("label_phase")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_phase)
        self.field_phase = QtWidgets.QLineEdit(self.widget_comps)
        self.field_phase.setMaximumSize(QtCore.QSize(150, 16777215))
        self.field_phase.setObjectName("field_phase")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.field_phase)
        self.gridLayout_settings.addLayout(self.formLayout_3, 3, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_settings.addItem(spacerItem4, 0, 0, 1, 2)
        self.list_sig_components = QtWidgets.QListWidget(self.widget_comps)
        self.list_sig_components.setMaximumSize(QtCore.QSize(100, 16777215))
        self.list_sig_components.setObjectName("list_sig_components")
        self.gridLayout_settings.addWidget(self.list_sig_components, 3, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.btn_add_component = QtWidgets.QPushButton(self.widget_comps)
        self.btn_add_component.setObjectName("btn_add_component")
        self.gridLayout_settings.addWidget(self.btn_add_component, 4, 0, 1, 1)
        self.label_component_list = QtWidgets.QLabel(self.widget_comps)
        self.label_component_list.setObjectName("label_component_list")
        self.gridLayout_settings.addWidget(self.label_component_list, 2, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_settings.addItem(spacerItem5, 5, 0, 1, 2)
        self.verticalLayout_8.addLayout(self.gridLayout_settings)
        self.gridLayout_3.addWidget(self.widget_comps, 0, 1, 1, 1)
        self.tabWidget.addTab(self.tab_composer, "")
        self.gridLayout_6.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAdd_Signal = QtWidgets.QAction(MainWindow)
        self.actionAdd_Signal.setObjectName("actionAdd_Signal")

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.field_name, self.field_amplitude)
        MainWindow.setTabOrder(self.field_amplitude, self.field_frequency)
        MainWindow.setTabOrder(self.field_frequency, self.field_phase)
        MainWindow.setTabOrder(self.field_phase, self.btn_add_component)
        MainWindow.setTabOrder(self.btn_add_component, self.list_sig_components)
        MainWindow.setTabOrder(self.list_sig_components, self.btn_remove_component)
        MainWindow.setTabOrder(self.btn_remove_component, self.btn_compose)
        MainWindow.setTabOrder(self.btn_compose, self.dial_SNR)
        MainWindow.setTabOrder(self.dial_SNR, self.btn_open_signal)
        MainWindow.setTabOrder(self.btn_open_signal, self.horizontalSlider_sample_freq)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lbl_snr_level.setText(_translate("MainWindow", "SNR Level (dB)"))
        self.btn_open_signal.setText(_translate("MainWindow", "Open Signal"))
        self.label_original_frequency.setText(_translate("MainWindow", "Max Frequency: "))
        self.label_sampling_frequency.setText(_translate("MainWindow", "Sampling Frequency:"))
        self.label_main_signal.setText(_translate("MainWindow", "Main Signal:"))
        self.label_constructed_signal.setText(_translate("MainWindow", "Constructed Signal:"))
        self.label_const_err.setText(_translate("MainWindow", "Error In Construction:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_viewer), _translate("MainWindow", "Signal Viewer"))
        self.label.setText(_translate("MainWindow", "Component Preview:"))
        self.label_2.setText(_translate("MainWindow", "Composed Signal Preview:"))
        self.btn_compose.setText(_translate("MainWindow", "Save Composed Signal"))
        self.btn_remove_component.setText(_translate("MainWindow", "Remove Component"))
        self.label_comp_stats.setText(_translate("MainWindow", "Component Characteristics:"))
        self.label_phase_2.setText(_translate("MainWindow", "Comp name"))
        self.label_amp.setText(_translate("MainWindow", "Amplitude"))
        self.label_freq.setText(_translate("MainWindow", "Frequency(Hz)"))
        self.label_phase.setText(_translate("MainWindow", "Phase°"))
        self.btn_add_component.setText(_translate("MainWindow", "Add Component"))
        self.label_component_list.setText(_translate("MainWindow", "Component List:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_composer), _translate("MainWindow", "Signal Composer"))
        self.actionAdd_Signal.setText(_translate("MainWindow", "Add Signal"))
from pyqtgraph import PlotWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
